import {
	ArrowRight,
	Bookmark,
	Check,
	ChevronDown,
	Clock3,
	Download,
	FileText,
	Globe2,
	Heart,
	Languages,
	LockKeyhole,
	Play,
	RotateCcw,
	Share2,
	ShieldCheck,
	Star,
	Users,
	Video,
} from 'lucide-react';
import { useState } from 'react';
import StudentDashboardFooter from '../../components/layout/StudentDashboardFooter';
import StudentDashboardHeader from '../../components/layout/StudentDashboardHeader';

const outcomes = ['Build production-ready AI agents with the Model Context Protocol.', 'Connect tools, resources, and prompts to intelligent workflows.', 'Deploy and debug agentic applications with confidence.', 'Create practical projects using modern AI development patterns.', 'Understand the fundamentals of MCP servers and clients.', 'Prepare for real-world AI engineering opportunities.'];
const curriculum = [['Welcome to the course', '3 lectures', '18 min'], ['MCP fundamentals and architecture', '6 lectures', '42 min'], ['Building your first MCP server', '8 lectures', '1 hr 12 min'], ['Tools, resources, and prompts', '7 lectures', '58 min'], ['Building production-ready agents', '9 lectures', '1 hr 24 min'], ['Deploying and testing your project', '6 lectures', '48 min'], ['Final project: Build a complete AI agent', '5 lectures', '1 hr 10 min']];
const relatedCourses = [['AI Engineering Production Track', '/images/students.png', '$39.99'], ['AI Agents Complete Guide', '/images/about.png', '$29.99'], ['Python for Data Science', '/images/Certificate.png', '$24.99'], ['Machine Learning Foundations', '/images/students.png', '$34.99']];

export default function StudentCourseDetails() {
	const [isProfileMenuOpen, setIsProfileMenuOpen] = useState(false);
	const [isSaved, setIsSaved] = useState(false);
	const [openSection, setOpenSection] = useState(0);

	return (
		<div className="min-h-screen bg-[#f5f4f1] text-[#101010]">
			<StudentDashboardHeader onOpenMenu={() => setIsProfileMenuOpen(true)} />
			{isProfileMenuOpen ? <button type="button" aria-label="Close profile menu" onClick={() => setIsProfileMenuOpen(false)} className="fixed inset-0 z-40 bg-black/10" /> : null}
			<main className="mx-auto max-w-[1400px] px-4 pb-12 pt-4 sm:px-6 lg:px-8 lg:pt-6">
				<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
					<div className="min-w-0 space-y-5">
						<section className="overflow-hidden rounded-[10px] border border-black/10 bg-[#111827] text-white shadow-[0_18px_45px_rgba(0,0,0,0.16)]"><div className="grid lg:grid-cols-[1.1fr_0.9fr]"><div className="relative min-h-[270px] overflow-hidden p-6 sm:p-8"><img src="/images/about.png" alt="AI engineering course" className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="absolute inset-0 bg-[linear-gradient(110deg,#111827_18%,rgba(17,24,39,0.82),rgba(17,24,39,0.3))]" /><div className="relative max-w-xl"><div className="flex flex-wrap gap-2 text-[11px] font-bold uppercase tracking-[0.16em]"><span className="rounded bg-[#F5A800] px-2 py-1 text-black">Bestseller</span><span className="rounded border border-white/20 px-2 py-1 text-white/75">AI Engineering</span></div><h1 className="mt-5 text-3xl font-black leading-tight sm:text-[2.55rem]">AI Engineer Agentic Track: The Complete Agent + MCP Course</h1><p className="mt-3 max-w-lg text-sm leading-6 text-white/72">Master the tools and techniques needed to build intelligent, autonomous AI agents from the ground up.</p><div className="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-white/70"><span className="inline-flex items-center gap-1 text-[#F5A800]"><Star size={14} fill="currentColor" /> 4.8</span><span>1,240 ratings</span><span>8,642 students</span><span>English</span></div></div></div><div className="relative flex min-h-[220px] items-center justify-center bg-black/20 p-6"><img src="/images/students.png" alt="Students learning AI engineering" className="absolute inset-0 h-full w-full object-cover opacity-60" /><button type="button" className="relative flex h-16 w-16 items-center justify-center rounded-full bg-[#F5A800] text-black shadow-[0_10px_30px_rgba(245,168,0,0.4)]" aria-label="Preview course"><Play size={26} fill="currentColor" /></button><span className="absolute bottom-5 rounded bg-black/70 px-3 py-1 text-xs font-semibold">Preview this course</span></div></div></section>
						<nav className="flex gap-6 overflow-x-auto border-b border-black/10 bg-white px-4 text-sm font-semibold whitespace-nowrap sm:px-6"><a className="border-b-2 border-[#F5A800] py-4 text-black" href="#overview">Overview</a><a className="py-4 text-black/50" href="#curriculum">Curriculum</a><a className="py-4 text-black/50" href="#reviews">Reviews</a><a className="py-4 text-black/50" href="#instructor">Instructor</a></nav>
						<section id="overview" className="rounded-[10px] border border-black/8 bg-white p-5 shadow-[0_10px_28px_rgba(0,0,0,0.04)] sm:p-6"><h2 className="text-xl font-extrabold">What you'll learn</h2><div className="mt-4 grid gap-x-8 gap-y-3 sm:grid-cols-2">{outcomes.map((outcome) => <div key={outcome} className="flex gap-2 text-sm leading-5 text-black/65"><Check size={16} className="mt-0.5 shrink-0 text-[#F5A800]" />{outcome}</div>)}</div></section>
						<section className="grid grid-cols-2 gap-3 rounded-[10px] border border-black/8 bg-white p-5 sm:grid-cols-4 sm:p-6"><CourseStat icon={Clock3} label="Duration" value="12 hours" /><CourseStat icon={Video} label="Lectures" value="44 lessons" /><CourseStat icon={FileText} label="Certificate" value="On completion" /><CourseStat icon={Globe2} label="Access" value="Lifetime" /></section>
						<section id="curriculum" className="rounded-[10px] border border-black/8 bg-white p-5 shadow-[0_10px_28px_rgba(0,0,0,0.04)] sm:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-extrabold">Course content</h2><p className="mt-1 text-xs text-black/45">7 sections • 44 lectures • 12h 34m total length</p></div><button type="button" className="text-xs font-bold text-[#C88900]">Expand all sections</button></div><div className="mt-5 overflow-hidden rounded border border-black/10">{curriculum.map(([title, lessons, duration], index) => <div key={title} className="border-b border-black/8 last:border-0"><button type="button" onClick={() => setOpenSection(openSection === index ? -1 : index)} className="flex w-full items-center justify-between gap-3 bg-[#fafaf8] px-4 py-4 text-left text-sm font-bold"><span className="flex items-center gap-3"><ChevronDown size={16} className={`transition ${openSection === index ? 'rotate-180 text-[#F5A800]' : 'text-black/40'}`} />{title}</span><span className="text-xs font-medium text-black/45">{lessons} • {duration}</span></button>{openSection === index ? <div className="flex items-center gap-3 px-12 pb-4 text-xs text-black/55"><Play size={14} className="text-[#F5A800]" /> Introduction and learning objectives</div> : null}</div>)}</div><button type="button" className="mt-4 flex w-full items-center justify-center gap-2 rounded border border-black/15 py-3 text-sm font-bold hover:bg-black/[0.03]"><Play size={15} /> Preview first lecture</button></section>
						<section className="rounded-[10px] border border-black/8 bg-white p-5 sm:p-6"><h2 className="text-xl font-extrabold">Requirements</h2><ul className="mt-4 space-y-2 text-sm text-black/65"><li>Basic understanding of programming concepts.</li><li>A computer with internet access.</li><li>Curiosity and a desire to build with AI.</li></ul><div className="mt-7 border-t border-black/8 pt-6"><h2 className="text-xl font-extrabold">Description</h2><p className="mt-3 text-sm leading-7 text-black/65">Take a practical journey through the world of agentic AI. This complete course teaches you how to design, build, connect, and deploy AI agents with the Model Context Protocol.</p><p className="mt-3 text-sm leading-7 text-black/65">From the fundamentals to a complete final project, every lesson is designed to help you turn ideas into useful products and real-world skills.</p></div></section>
						<section id="instructor" className="rounded-[10px] border border-black/8 bg-white p-5 sm:p-6"><h2 className="text-xl font-extrabold">About the instructor</h2><div className="mt-5 flex flex-col gap-5 sm:flex-row"><img src="/images/about.png" alt="Ed Donner" className="h-24 w-24 rounded-full object-cover" /><div><h3 className="text-lg font-extrabold">Ed Donner</h3><p className="mt-1 text-sm text-[#C88900]">AI Engineer & Educator</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-black/55"><span><Star size={13} className="mr-1 inline text-[#F5A800]" fill="currentColor" />4.8 Instructor rating</span><span><Users size={13} className="mr-1 inline text-[#F5A800]" />42,000+ students</span><span><Video size={13} className="mr-1 inline text-[#F5A800]" />8 courses</span></div></div><p className="max-w-xl text-sm leading-6 text-black/60 sm:ml-auto sm:w-2/5">Ed has spent more than a decade building software and teaching developers how to use emerging technology with clarity and confidence.</p></div></section>
						<section id="reviews" className="rounded-[10px] border border-black/8 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">Ratings and reviews</h2><span className="text-sm font-bold text-[#C88900]">See all reviews</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{['A practical and brilliantly structured course.', 'The projects made the concepts easy to apply.', 'Excellent explanations and useful examples.'].map((review, index) => <article key={review} className="rounded border border-black/8 p-4"><div className="flex gap-0.5 text-[#F5A800]">{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={13} fill="currentColor" />)}</div><p className="mt-3 text-sm leading-5 text-black/65">{review}</p><p className="mt-3 text-xs font-bold text-black/45">{['Michael R.', 'Sarah K.', 'David P.'][index]}</p></article>)}</div></section>
						<section className="rounded-[10px] border border-black/8 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">More courses by <span className="text-[#C88900]">Ed Donner</span></h2><div className="flex gap-2"><button type="button" aria-label="Previous courses" className="rounded-full border p-2"><ArrowRight size={14} className="rotate-180" /></button><button type="button" aria-label="Next courses" className="rounded-full border p-2"><ArrowRight size={14} /></button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{relatedCourses.map(([title, image, price]) => <article key={title} className="overflow-hidden rounded border border-black/8"><img src={image} alt="" className="h-28 w-full object-cover" /><div className="p-3"><h3 className="line-clamp-2 text-sm font-bold leading-5">{title}</h3><div className="mt-2 flex items-center justify-between text-xs"><span className="text-[#F5A800]">★★★★★</span><b>{price}</b></div></div></article>)}</div></section>
					</div>
					<aside className="h-fit space-y-4 xl:sticky xl:top-24"><section className="overflow-hidden rounded-[10px] border border-black/10 bg-white shadow-[0_15px_40px_rgba(0,0,0,0.1)]"><div className="p-5 sm:p-6"><div className="flex items-end gap-3"><span className="text-3xl font-black">$13.30</span><span className="text-sm text-black/35 line-through">$79.99</span><span className="rounded bg-[#fff3cf] px-2 py-1 text-xs font-bold text-[#a66b00]">83% off</span></div><p className="mt-2 text-xs font-semibold text-[#d74932]">2 days left at this price!</p><button type="button" className="mt-5 flex w-full items-center justify-center rounded bg-[#F5A800] py-3.5 text-sm font-extrabold text-black shadow-[0_8px_20px_rgba(245,168,0,0.25)] hover:bg-[#ffbc25]">Start Subscription</button><button type="button" className="mt-2 flex w-full items-center justify-center gap-2 rounded border border-black/15 py-3 text-sm font-bold">Add to cart</button><button type="button" onClick={() => setIsSaved(!isSaved)} className="mt-2 flex w-full items-center justify-center gap-2 rounded border border-black/15 py-3 text-sm font-bold"><Heart size={15} fill={isSaved ? 'currentColor' : 'none'} className={isSaved ? 'text-[#d74932]' : ''} /> {isSaved ? 'Saved to wishlist' : 'Save to wishlist'}</button><div className="mt-6 border-t border-black/8 pt-5"><h3 className="text-sm font-bold">This course includes:</h3><ul className="mt-3 space-y-3 text-xs text-black/65"><li><Video size={14} className="mr-2 inline text-[#F5A800]" />12 hours on-demand video</li><li><Download size={14} className="mr-2 inline text-[#F5A800]" />Downloadable resources</li><li><Languages size={14} className="mr-2 inline text-[#F5A800]" />English subtitles</li><li><LockKeyhole size={14} className="mr-2 inline text-[#F5A800]" />Lifetime access</li><li><ShieldCheck size={14} className="mr-2 inline text-[#F5A800]" />Certificate of completion</li></ul></div><p className="mt-5 text-center text-[11px] text-black/45">30-day money-back guarantee</p></div></section><section className="rounded-[10px] border border-black/8 bg-white p-5"><h3 className="text-sm font-extrabold">Share this course</h3><div className="mt-3 flex gap-2"><button type="button" className="flex-1 rounded border py-2 text-xs font-bold"><Share2 size={14} className="mr-1 inline" /> Share</button><button type="button" className="flex-1 rounded border py-2 text-xs font-bold"><Bookmark size={14} className="mr-1 inline" /> Save</button></div></section><section className="rounded-[10px] border border-[#F5A800]/30 bg-[#fff8e4] p-5"><div className="flex gap-3"><RotateCcw size={22} className="shrink-0 text-[#C88900]" /><div><h3 className="text-sm font-extrabold">30-day Money-Back Guarantee</h3><p className="mt-2 text-xs leading-5 text-black/60">Not satisfied? Get a full refund within 30 days, no questions asked.</p></div></div></section></aside>
				</div>
			</main>
			<StudentDashboardFooter />
		</div>
	);
}

function CourseStat({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) {
	return <div className="flex items-center gap-3 border-r border-black/8 px-2 last:border-0"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#fff4cf] text-[#C88900]"><Icon size={18} /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-black/40">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div></div>;
}
