import { ChevronDown, MessageSquare, MoreHorizontal, Star, ThumbsUp, Users } from 'lucide-react';
import LectureDashboardFooter from '../../components/layout/LectureDashboardFooter';
import LectureDashboardHeader from '../../components/layout/LectureDashboardHeader';

const reviews = [
	{ initials: 'SJ', name: 'Sarah Johnson', course: 'AI Engineer Agentic Track', time: '2 days ago', rating: 5, text: 'Excellent course! The content is incredibly well-structured and easy to follow. John explains complex AI concepts in a very clear and practical way.', tags: ['Clear Explanations', 'Great Examples', 'Well Structured'], likes: 24, replies: 2 },
	{ initials: 'MC', name: 'Mike Chen', course: 'Machine Learning Masterclass', time: '5 days ago', rating: 4, text: 'Great course with practical examples. The hands-on projects were especially helpful. You get to see more advanced topics!', tags: ['Practical', 'Hands-on Projects', 'Good Pace'], likes: 18, replies: 1 },
	{ initials: 'ER', name: 'Emily Rodriguez', course: 'Python for AI & ML', time: '1 week ago', rating: 5, text: 'John is an amazing instructor! His teaching style keeps you engaged throughout the course. Highly recommended!', tags: ['Engaging', 'Easy to Understand', 'Highly Recommended'], likes: 31, replies: 3 },
	{ initials: 'DK', name: 'David Kumar', course: 'Deep Learning Fundamentals', time: '1 week ago', rating: 4, text: 'Very comprehensive course covering all the fundamentals. The visual explanations and code examples are top-notch.', tags: ['Comprehensive', 'Great Visuals', 'Well Explained'], likes: 15, replies: 0 },
	{ initials: 'LW', name: 'Lisa Wang', course: 'AI Engineer Agentic Track', time: '2 weeks ago', rating: 5, text: 'This course exceeded my expectations! I was able to build my own AI agent by the end of the course.', tags: ['Project Based', 'Practical', 'Excellent Support'], likes: 22, replies: 1 },
];

const breakdown = [['5 Stars', '78%', '975'], ['4 Stars', '17%', '215'], ['3 Stars', '4%', '50'], ['2 Stars', '1%', '8'], ['1 Star', '0%', '3']];
const categories = [['Clear Explanations', '4.9'], ['Teaching Style', '4.8'], ['Course Content', '4.8'], ['Practical Examples', '4.7'], ['Engagement', '4.8'], ['Value for Money', '4.6']];

export default function LectureReviews() {
	return <div className="min-h-screen bg-[#fbfbfa] text-[#172033]"><LectureDashboardHeader /><main className="mx-auto max-w-[1280px] px-4 pb-12 pt-5 sm:px-6 lg:px-8">
		<div className="mb-5"><div className="flex items-center gap-2 text-[9px] text-[#172033]/45"><span>Dashboard</span><span>›</span><span>Instructor</span><span>›</span><span className="font-semibold text-[#172033]/75">Reviews &amp; Rating</span></div><h1 className="mt-2 text-2xl font-extrabold tracking-[-0.04em] sm:text-[28px]">Reviews &amp; Rating</h1><p className="mt-1 text-xs text-[#172033]/55">See what your students are saying about your courses.</p></div>
		<InstructorBanner />
		<div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['☆', '1,248', 'Total Reviews'], ['☺', '98%', 'Students Recommend'], ['▱', '96%', 'Positive Reviews'], ['◷', '24h', 'Avg. Response Time']].map(([icon, value, label]) => <div key={label} className="flex items-center gap-3 rounded-lg border border-[#172033]/8 bg-white px-3 py-3 shadow-[0_4px_16px_rgba(23,32,51,0.025)] sm:px-4"><span className="text-2xl text-[#f5a800]">{icon}</span><div><p className="text-lg font-extrabold leading-none">{value}</p><p className="mt-1 text-[8px] text-[#172033]/50">{label}</p></div></div>)}</div>
		<div className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="overflow-hidden rounded-lg border border-[#172033]/8 bg-white shadow-[0_5px_18px_rgba(23,32,51,0.03)]"><div className="flex flex-col gap-3 border-b border-[#172033]/8 px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-bold">All Student Reviews</h2><p className="mt-1 text-[9px] text-[#172033]/50">Latest reviews from your students</p></div><div className="flex gap-2"><Select label="All Courses" /><Select label="Most Recent" /></div></div><div>{reviews.map((review) => <ReviewRow key={review.name} review={review} />)}</div><div className="flex items-center justify-center gap-2 border-t border-[#172033]/8 px-4 py-3 text-[9px]"><button type="button" className="flex h-6 w-6 items-center justify-center rounded-full border border-[#172033]/10">‹</button>{['1', '2', '3', '…', '42'].map((page) => <button key={page} type="button" className={`flex h-6 w-6 items-center justify-center rounded-full font-bold ${page === '1' ? 'bg-[#f5a800] text-[#111111]' : 'text-[#172033]/60'}`}>{page}</button>)}<button type="button" className="flex h-6 w-6 items-center justify-center rounded-full border border-[#172033]/10">›</button></div></section><aside className="space-y-4"><RatingBreakdown /><CategoryRatings /><PositiveCard /></aside></div>
	</main><LectureDashboardFooter /></div>;
}

function InstructorBanner() { return <section className="relative overflow-hidden rounded-xl bg-[#161718] p-5 text-white shadow-[0_10px_25px_rgba(0,0,0,0.13)] sm:p-6"><div className="absolute -right-8 -top-16 h-64 w-64 rounded-full border border-[#f5a800]/35" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-28 w-24 shrink-0 items-center justify-center rounded-lg bg-[#f5a800] text-3xl font-black text-[#111111]">JD</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">John Doe</h2><span className="rounded bg-[#f5a800]/20 px-2 py-1 text-[8px] font-bold text-[#f5a800]">Instructor</span></div><p className="mt-1 text-[10px] text-white/80">AI Enthusiast &amp; Educator</p><p className="mt-3 max-w-xl text-[10px] leading-4 text-white/65">Creating engaging courses on Artificial Intelligence, Machine Learning<br className="hidden sm:block" /> and the future of technology.</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[9px] text-white/70"><span>▣ &nbsp;24 Courses</span><span><Users size={11} className="mr-1 inline" />12.4K Students</span><span>▣ &nbsp;Joined IOEL in 2022</span></div></div><div className="border-t border-white/10 pt-4 text-center sm:border-l sm:border-t-0 sm:pl-8 sm:pt-0"><p className="text-[9px] text-white/70"><Star size={11} className="mr-1 inline fill-[#f5a800] text-[#f5a800]" />Overall Rating</p><p className="mt-1 text-4xl font-black">4.8<span className="text-lg font-normal">/5</span></p><p className="text-lg tracking-[0.18em] text-[#f5a800]">★★★★★</p><p className="mt-1 text-[8px] text-white/55">Based on 1,248 reviews</p></div></div></section>; }
function ReviewRow({ review }: { review: typeof reviews[number] }) { return <article className="border-b border-[#172033]/8 px-4 py-4 last:border-0 sm:px-5"><div className="flex gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#e8eef4] text-[9px] font-bold text-[#172033]">{review.initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-[10px] font-bold">{review.name}</p><p className="mt-0.5 text-[8px] font-semibold text-[#3567c8]">{review.course}</p></div><span className="text-[8px] text-[#172033]/45">{review.time}</span></div><div className="mt-2 text-sm tracking-[0.1em] text-[#f5a800]">{'★'.repeat(review.rating)}<span className="text-[#e1e4e9]">{'★'.repeat(5 - review.rating)}</span></div><p className="mt-1.5 text-[9px] leading-4 text-[#172033]/70">{review.text}</p><div className="mt-2 flex flex-wrap gap-1.5">{review.tags.map((tag) => <span key={tag} className="rounded bg-[#edf7ef] px-2 py-1 text-[7px] font-medium text-[#3b7653]">{tag}</span>)}</div><div className="mt-3 flex items-center gap-4 text-[8px] text-[#172033]/45"><span>Was this review helpful?</span><button type="button" className="inline-flex items-center gap-1 hover:text-[#172033]"><ThumbsUp size={11} />{review.likes}</button><button type="button" className="inline-flex items-center gap-1 hover:text-[#172033]"><MessageSquare size={11} />{review.replies}</button><button type="button" className="ml-auto"><MoreHorizontal size={13} /></button></div></div></div></article>; }
function Select({ label }: { label: string }) { return <button type="button" className="inline-flex items-center gap-2 rounded border border-[#172033]/10 px-2.5 py-1.5 text-[8px] font-medium text-[#172033]/65">{label}<ChevronDown size={11} /></button>; }
function RatingBreakdown() { return <Panel title="Rating Breakdown"><div className="flex items-center gap-3 border-b border-[#172033]/8 pb-3"><div className="flex h-16 w-16 items-center justify-center rounded-full border-[6px] border-[#f5a800] text-center"><span className="text-base font-extrabold">4.8<small className="block text-[7px] font-normal text-[#172033]/45">Overall</small></span></div><div className="text-[8px] text-[#172033]/50">Based on<br /><strong className="text-[#172033]">1,248 reviews</strong></div></div><div className="mt-3 space-y-2">{breakdown.map(([label, percent, count]) => <div key={label} className="flex items-center gap-2 text-[8px] text-[#172033]/55"><span className="w-9">{label}</span><span className="h-1.5 flex-1 rounded-full bg-[#edf0f3]"><span className="block h-full rounded-full bg-[#f5a800]" style={{ width: percent }} /></span><span className="w-12 text-right">{percent} ({count})</span></div>)}</div></Panel>; }
function CategoryRatings() { return <Panel title="Category Ratings"><div className="mt-2 space-y-3">{categories.map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-[#172033]/6 pb-2 text-[8px] last:border-0 last:pb-0"><span>{label}</span><span className="font-bold">{value} <Star size={9} className="inline fill-[#f5a800] text-[#f5a800]" /></span></div>)}</div></Panel>; }
function PositiveCard() { return <Panel title="Top Positives"><div className="mt-2 space-y-3 text-[8px] text-[#172033]/65">{[['Clear & Easy to Understand', '98%'], ['Practical & Hands-on', '96%'], ['Engaging Teaching Style', '95%'], ['Well Structured Content', '94%'], ['Responsive Instructor', '93%']].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-2"><span>▣ &nbsp;{label}</span><strong>{value}</strong></div>)}</div><p className="mt-4 text-[7px] text-[#172033]/40">Percentages based on student feedback</p></Panel>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-lg border border-[#172033]/8 bg-white p-4 shadow-[0_5px_18px_rgba(23,32,51,0.025)]"><h2 className="text-[11px] font-bold">{title}</h2>{children}</section>; }
